// ---------------------------------------------------------------------------
// JTFA High Protein Recipe Pack — structured recipe data
// Source: JT Fitness Academy recipe pack (52 recipes)
// Tags: GF=Gluten Free, DF=Dairy Free, LC=Low Carb, MP=Meal Prep,
//       HP=High Protein, V=Vegetarian, Q=Quick, N=No Cook
// ---------------------------------------------------------------------------

export type RecipeTag = "GF" | "DF" | "LC" | "MP" | "HP" | "V" | "Q" | "N";
export type RecipeCategory = "breakfast" | "lunch" | "dinner" | "snack" | "smoothie";

export interface RecipeNutrition {
  calories: number;
  protein: number; // grams
  carbs: number;   // grams
  fat: number;     // grams
}

export interface Recipe {
  id: string;
  name: string;
  category: RecipeCategory;
  tags: RecipeTag[];
  servings: number;
  prepMins: number;
  cookMins: number;
  nutrition: RecipeNutrition; // per serving
  ingredients: string[];
  instructions: string[];
  tip?: string;
}

export const recipes: Recipe[] = [
  // ── BREAKFAST ──────────────────────────────────────────────────────────────
  {
    id: "b1",
    name: "Greek Yogurt Protein Bowl",
    category: "breakfast",
    tags: ["HP", "V", "Q", "GF"],
    servings: 1,
    prepMins: 5,
    cookMins: 0,
    nutrition: { calories: 380, protein: 38, carbs: 32, fat: 8 },
    ingredients: [
      "250g fat-free Greek yogurt",
      "30g vanilla protein powder",
      "80g mixed berries",
      "20g granola",
      "1 tbsp honey",
      "1 tbsp chia seeds",
    ],
    instructions: [
      "Mix protein powder into Greek yogurt until smooth.",
      "Top with mixed berries, granola, chia seeds, and a drizzle of honey.",
      "Serve immediately.",
    ],
    tip: "Prep the yogurt and protein mix the night before — just add toppings in the morning.",
  },
  {
    id: "b2",
    name: "Egg White & Spinach Omelette",
    category: "breakfast",
    tags: ["HP", "GF", "DF", "LC", "Q"],
    servings: 1,
    prepMins: 5,
    cookMins: 8,
    nutrition: { calories: 220, protein: 30, carbs: 4, fat: 8 },
    ingredients: [
      "6 egg whites",
      "2 whole eggs",
      "80g fresh spinach",
      "50g cherry tomatoes, halved",
      "30g reduced-fat feta cheese",
      "Salt and pepper to taste",
      "1 tsp olive oil",
    ],
    instructions: [
      "Whisk egg whites and whole eggs together with salt and pepper.",
      "Heat olive oil in a non-stick pan over medium heat.",
      "Add spinach and tomatoes, sauté 1 minute until wilted.",
      "Pour egg mixture over vegetables, cook until edges set.",
      "Sprinkle feta, fold omelette in half, serve immediately.",
    ],
  },
  {
    id: "b3",
    name: "Overnight Protein Oats",
    category: "breakfast",
    tags: ["HP", "V", "MP", "Q"],
    servings: 1,
    prepMins: 5,
    cookMins: 0,
    nutrition: { calories: 430, protein: 35, carbs: 52, fat: 8 },
    ingredients: [
      "70g rolled oats",
      "30g chocolate protein powder",
      "200ml skimmed milk",
      "100g low-fat Greek yogurt",
      "1 tbsp peanut butter",
      "1 medium banana, sliced",
    ],
    instructions: [
      "Combine oats, protein powder, milk, and yogurt in a jar.",
      "Stir well, seal and refrigerate overnight (minimum 6 hours).",
      "In the morning, top with sliced banana and peanut butter.",
    ],
    tip: "Make 5 jars on Sunday for the whole work week.",
  },
  {
    id: "b4",
    name: "Turkey Bacon & Egg Muffins",
    category: "breakfast",
    tags: ["HP", "GF", "MP", "Q"],
    servings: 2,
    prepMins: 10,
    cookMins: 20,
    nutrition: { calories: 290, protein: 32, carbs: 6, fat: 14 },
    ingredients: [
      "6 large eggs",
      "4 rashers turkey bacon, chopped",
      "50g reduced-fat cheddar, grated",
      "40g bell pepper, diced",
      "2 tbsp fresh chives, chopped",
      "Salt and pepper",
    ],
    instructions: [
      "Preheat oven to 180°C. Grease a 6-hole muffin tin.",
      "Whisk eggs with salt and pepper.",
      "Divide turkey bacon, pepper, and chives across the muffin holes.",
      "Pour egg mixture over fillings, top with cheddar.",
      "Bake 18–20 minutes until set and golden.",
    ],
    tip: "Store in the fridge up to 4 days. Reheat 30 seconds in the microwave.",
  },
  {
    id: "b5",
    name: "Cottage Cheese Pancakes",
    category: "breakfast",
    tags: ["HP", "V", "GF", "Q"],
    servings: 1,
    prepMins: 5,
    cookMins: 10,
    nutrition: { calories: 340, protein: 34, carbs: 28, fat: 10 },
    ingredients: [
      "150g low-fat cottage cheese",
      "2 large eggs",
      "40g oat flour",
      "1 tsp vanilla extract",
      "1 tsp baking powder",
      "100g fresh strawberries to serve",
    ],
    instructions: [
      "Blend cottage cheese, eggs, vanilla, oat flour, and baking powder until smooth.",
      "Heat a non-stick pan over medium-low heat, lightly spray with cooking spray.",
      "Pour 3–4 small pancakes, cook 2–3 minutes each side until golden.",
      "Serve topped with sliced strawberries.",
    ],
  },
  {
    id: "b6",
    name: "High Protein Smoothie Bowl",
    category: "breakfast",
    tags: ["HP", "V", "GF", "DF", "Q", "N"],
    servings: 1,
    prepMins: 5,
    cookMins: 0,
    nutrition: { calories: 360, protein: 32, carbs: 40, fat: 6 },
    ingredients: [
      "150g frozen mixed berries",
      "1 frozen banana",
      "30g vanilla protein powder",
      "100ml unsweetened almond milk",
      "Toppings: 15g hemp seeds, 30g granola, fresh kiwi slices",
    ],
    instructions: [
      "Blend frozen berries, banana, protein powder, and almond milk until thick and smooth.",
      "Pour into a bowl — it should be thick enough to hold toppings.",
      "Arrange hemp seeds, granola, and kiwi on top.",
    ],
  },

  // ── LUNCH ──────────────────────────────────────────────────────────────────
  {
    id: "l1",
    name: "Chicken & Quinoa Power Bowl",
    category: "lunch",
    tags: ["HP", "GF", "DF", "MP"],
    servings: 2,
    prepMins: 10,
    cookMins: 25,
    nutrition: { calories: 480, protein: 46, carbs: 42, fat: 10 },
    ingredients: [
      "300g chicken breast, sliced",
      "150g quinoa (dry weight)",
      "1 red bell pepper, sliced",
      "1 courgette, sliced",
      "80g edamame beans",
      "2 tbsp light soy sauce",
      "1 tbsp olive oil",
      "1 tsp garlic powder",
      "Juice of 1 lime",
    ],
    instructions: [
      "Cook quinoa per packet instructions.",
      "Season chicken with garlic powder, salt, and pepper.",
      "Heat oil in a pan, cook chicken 5–6 minutes each side until cooked through. Slice.",
      "Sauté pepper and courgette in the same pan 3–4 minutes.",
      "Combine quinoa, vegetables, and edamame in bowls.",
      "Top with chicken, drizzle soy sauce and lime juice.",
    ],
    tip: "Meal prep for 4 portions — keeps 4 days in the fridge.",
  },
  {
    id: "l2",
    name: "Tuna & Avocado Rice Cakes",
    category: "lunch",
    tags: ["HP", "GF", "DF", "LC", "Q", "N"],
    servings: 1,
    prepMins: 5,
    cookMins: 0,
    nutrition: { calories: 310, protein: 34, carbs: 18, fat: 10 },
    ingredients: [
      "2 cans tuna in spring water (drained, 160g drained weight)",
      "½ avocado, mashed",
      "1 tbsp lemon juice",
      "6 rice cakes",
      "Handful of rocket leaves",
      "Salt and pepper",
    ],
    instructions: [
      "Mix tuna with mashed avocado and lemon juice. Season with salt and pepper.",
      "Spread tuna mix onto rice cakes.",
      "Top with rocket leaves and serve.",
    ],
  },
  {
    id: "l3",
    name: "Lean Turkey Mince Stir Fry",
    category: "lunch",
    tags: ["HP", "DF", "LC", "Q", "MP"],
    servings: 2,
    prepMins: 10,
    cookMins: 15,
    nutrition: { calories: 390, protein: 42, carbs: 22, fat: 12 },
    ingredients: [
      "400g lean turkey mince (5% fat)",
      "200g tenderstem broccoli",
      "1 red onion, sliced",
      "2 garlic cloves, minced",
      "1 tbsp sesame oil",
      "2 tbsp soy sauce",
      "1 tbsp oyster sauce",
      "1 tsp fresh ginger, grated",
      "1 tsp chilli flakes (optional)",
    ],
    instructions: [
      "Heat sesame oil in a wok over high heat.",
      "Add onion and garlic, cook 2 minutes.",
      "Add turkey mince, break up and cook until browned (8–10 minutes).",
      "Add broccoli, soy sauce, oyster sauce, ginger, and chilli.",
      "Stir fry 3–4 minutes until broccoli is tender-crisp.",
      "Serve with cauliflower rice for low carb, or brown rice.",
    ],
  },
  {
    id: "l4",
    name: "Prawn & Brown Rice Salad",
    category: "lunch",
    tags: ["HP", "GF", "DF", "MP"],
    servings: 2,
    prepMins: 10,
    cookMins: 20,
    nutrition: { calories: 420, protein: 38, carbs: 44, fat: 8 },
    ingredients: [
      "300g cooked king prawns",
      "160g brown rice (dry weight)",
      "100g cucumber, diced",
      "80g cherry tomatoes, halved",
      "½ red onion, finely sliced",
      "2 tbsp fresh coriander, chopped",
      "Dressing: 2 tbsp rice vinegar, 1 tbsp fish sauce, 1 tsp sesame oil, 1 tsp honey",
    ],
    instructions: [
      "Cook brown rice per packet instructions. Cool.",
      "Whisk together all dressing ingredients.",
      "Combine rice, prawns, cucumber, tomatoes, onion, and coriander.",
      "Drizzle dressing over salad and toss to combine.",
    ],
  },
  {
    id: "l5",
    name: "Smoked Salmon & Egg White Wrap",
    category: "lunch",
    tags: ["HP", "Q"],
    servings: 1,
    prepMins: 5,
    cookMins: 5,
    nutrition: { calories: 350, protein: 38, carbs: 24, fat: 10 },
    ingredients: [
      "120g smoked salmon",
      "4 egg whites, scrambled",
      "1 large wholegrain wrap",
      "50g low-fat cream cheese",
      "Handful of rocket",
      "1 tsp capers",
      "Squeeze of lemon",
    ],
    instructions: [
      "Scramble egg whites in a non-stick pan with a pinch of salt.",
      "Spread cream cheese across the wrap.",
      "Layer scrambled egg whites, smoked salmon, rocket, and capers.",
      "Squeeze lemon juice over, roll tightly and slice in half.",
    ],
  },
  {
    id: "l6",
    name: "High Protein Chicken Soup",
    category: "lunch",
    tags: ["HP", "GF", "DF", "MP", "LC"],
    servings: 4,
    prepMins: 15,
    cookMins: 35,
    nutrition: { calories: 310, protein: 40, carbs: 18, fat: 6 },
    ingredients: [
      "600g chicken breast, diced",
      "1.5L low-sodium chicken stock",
      "200g cannellini beans, drained",
      "2 carrots, diced",
      "3 celery stalks, sliced",
      "1 onion, diced",
      "3 garlic cloves, minced",
      "1 tsp dried thyme",
      "1 tsp dried rosemary",
      "100g kale, chopped",
    ],
    instructions: [
      "In a large pot, sauté onion and garlic 3 minutes.",
      "Add chicken, cook until sealed on all sides.",
      "Pour in stock, add carrots, celery, beans, and herbs.",
      "Bring to boil, reduce heat, simmer 25 minutes.",
      "Add kale in the last 5 minutes. Season to taste.",
    ],
    tip: "Batch cook and freeze in individual portions for quick high-protein lunches.",
  },

  // ── DINNER ─────────────────────────────────────────────────────────────────
  {
    id: "d1",
    name: "Baked Lemon Herb Salmon",
    category: "dinner",
    tags: ["HP", "GF", "DF", "LC", "MP"],
    servings: 2,
    prepMins: 10,
    cookMins: 18,
    nutrition: { calories: 420, protein: 44, carbs: 6, fat: 22 },
    ingredients: [
      "2 salmon fillets (180g each)",
      "2 tbsp olive oil",
      "Zest and juice of 1 lemon",
      "2 garlic cloves, minced",
      "1 tsp dried dill",
      "1 tsp dried parsley",
      "Salt and pepper",
      "200g asparagus to serve",
    ],
    instructions: [
      "Preheat oven to 200°C. Line a baking tray with foil.",
      "Mix olive oil, lemon zest, lemon juice, garlic, dill, and parsley.",
      "Place salmon on tray, spoon herb mix over each fillet.",
      "Arrange asparagus alongside, season all with salt and pepper.",
      "Bake 16–18 minutes until salmon flakes easily.",
    ],
  },
  {
    id: "d2",
    name: "Chicken & Sweet Potato Meal Prep",
    category: "dinner",
    tags: ["HP", "GF", "DF", "MP"],
    servings: 4,
    prepMins: 15,
    cookMins: 35,
    nutrition: { calories: 490, protein: 48, carbs: 46, fat: 8 },
    ingredients: [
      "800g chicken breast",
      "4 medium sweet potatoes",
      "2 heads broccoli, cut into florets",
      "2 tbsp olive oil",
      "2 tsp paprika",
      "1 tsp garlic powder",
      "1 tsp onion powder",
      "Salt and pepper",
    ],
    instructions: [
      "Preheat oven to 200°C.",
      "Cut sweet potatoes into wedges and toss with 1 tbsp olive oil, paprika, salt.",
      "Spread on a baking tray, roast 25 minutes.",
      "Rub chicken with remaining oil, garlic powder, onion powder, salt and pepper.",
      "Add chicken and broccoli to trays, roast further 20–25 minutes.",
      "Divide into 4 meal prep containers.",
    ],
    tip: "Keeps 4 days in the fridge. Add a different sauce each day to mix it up.",
  },
  {
    id: "d3",
    name: "Beef & Vegetable Stir Fry",
    category: "dinner",
    tags: ["HP", "DF", "LC"],
    servings: 2,
    prepMins: 15,
    cookMins: 12,
    nutrition: { calories: 440, protein: 42, carbs: 20, fat: 16 },
    ingredients: [
      "350g lean beef sirloin, thinly sliced",
      "200g mangetout",
      "1 red bell pepper, sliced",
      "100g baby corn",
      "3 spring onions, sliced",
      "2 garlic cloves, minced",
      "1 tbsp sesame oil",
      "2 tbsp low-sodium soy sauce",
      "1 tbsp oyster sauce",
      "1 tsp cornstarch",
    ],
    instructions: [
      "Mix soy sauce, oyster sauce, and cornstarch to make a sauce.",
      "Heat sesame oil in a wok on high heat until smoking.",
      "Cook beef in batches 2–3 minutes until browned. Set aside.",
      "Add garlic and all vegetables, stir fry 3–4 minutes.",
      "Return beef to wok, pour over sauce, toss everything together.",
      "Serve immediately over cauliflower rice or brown rice.",
    ],
  },
  {
    id: "d4",
    name: "Turkey Meatballs with Courgette Noodles",
    category: "dinner",
    tags: ["HP", "GF", "LC", "DF"],
    servings: 2,
    prepMins: 20,
    cookMins: 25,
    nutrition: { calories: 380, protein: 44, carbs: 14, fat: 14 },
    ingredients: [
      "400g lean turkey mince",
      "1 egg",
      "2 tbsp fresh parsley, chopped",
      "1 tsp garlic powder",
      "1 tsp Italian seasoning",
      "400g passata",
      "3 large courgettes, spiralised",
      "½ onion, finely diced",
      "2 garlic cloves, minced",
    ],
    instructions: [
      "Mix turkey mince, egg, parsley, garlic powder, Italian seasoning, salt and pepper.",
      "Roll into 20 balls and place on a lined baking tray.",
      "Bake at 200°C for 18–20 minutes until cooked through.",
      "In a pan, sauté onion and garlic 3 minutes, add passata, simmer 10 minutes.",
      "Lightly sauté courgette noodles in a pan 2–3 minutes — just to warm through.",
      "Serve meatballs and sauce over courgette noodles.",
    ],
  },
  {
    id: "d5",
    name: "Baked Cod with Roasted Veg",
    category: "dinner",
    tags: ["HP", "GF", "DF", "LC", "MP"],
    servings: 2,
    prepMins: 10,
    cookMins: 25,
    nutrition: { calories: 320, protein: 40, carbs: 18, fat: 7 },
    ingredients: [
      "2 cod fillets (180g each)",
      "1 red onion, cut into wedges",
      "1 courgette, sliced",
      "200g cherry tomatoes",
      "1 yellow pepper, sliced",
      "2 tbsp olive oil",
      "1 tsp smoked paprika",
      "1 lemon",
      "Fresh basil to serve",
    ],
    instructions: [
      "Preheat oven to 200°C.",
      "Toss all vegetables with 1.5 tbsp olive oil and smoked paprika. Roast 15 minutes.",
      "Push veg to edges of tray, place cod in the centre.",
      "Drizzle remaining oil over cod, squeeze lemon over everything.",
      "Roast a further 10–12 minutes until cod is opaque and flakes easily.",
      "Scatter fresh basil and serve.",
    ],
  },
  {
    id: "d6",
    name: "Prawn & Chickpea Curry",
    category: "dinner",
    tags: ["HP", "GF", "DF", "MP"],
    servings: 3,
    prepMins: 10,
    cookMins: 20,
    nutrition: { calories: 390, protein: 38, carbs: 32, fat: 10 },
    ingredients: [
      "350g raw king prawns",
      "400g chickpeas (drained weight)",
      "400ml light coconut milk",
      "400g tinned chopped tomatoes",
      "1 onion, diced",
      "3 garlic cloves, minced",
      "1 tbsp curry powder",
      "1 tsp cumin",
      "1 tsp turmeric",
      "1 tsp ginger paste",
      "Fresh coriander to serve",
    ],
    instructions: [
      "Sauté onion and garlic in a spray of oil 3–4 minutes until softened.",
      "Add curry powder, cumin, turmeric, and ginger — cook 1 minute stirring.",
      "Pour in coconut milk and tomatoes. Add chickpeas and simmer 12 minutes.",
      "Add prawns in the final 4 minutes until pink and cooked through.",
      "Serve with basmati rice or cauliflower rice, top with fresh coriander.",
    ],
  },
  {
    id: "d7",
    name: "Lean Beef Chilli",
    category: "dinner",
    tags: ["HP", "GF", "DF", "MP"],
    servings: 5,
    prepMins: 15,
    cookMins: 40,
    nutrition: { calories: 420, protein: 40, carbs: 36, fat: 10 },
    ingredients: [
      "600g extra-lean beef mince (5% fat)",
      "400g kidney beans, drained",
      "400g black beans, drained",
      "800g tinned chopped tomatoes",
      "1 large onion, diced",
      "3 garlic cloves, minced",
      "1 red pepper, diced",
      "2 tsp chilli powder",
      "2 tsp cumin",
      "1 tsp smoked paprika",
      "200ml beef stock",
    ],
    instructions: [
      "Brown beef mince in a large pot over high heat. Drain any excess fat.",
      "Add onion, garlic, and pepper — cook 4 minutes.",
      "Add all spices, stir for 1 minute.",
      "Pour in tomatoes and stock, add both types of beans.",
      "Bring to boil, reduce heat, simmer 30 minutes stirring occasionally.",
      "Serve with rice, jacket potato, or on its own.",
    ],
    tip: "Freezes perfectly. Double the batch for easy future meals.",
  },

  // ── SNACKS ─────────────────────────────────────────────────────────────────
  {
    id: "s1",
    name: "Protein Bliss Balls",
    category: "snack",
    tags: ["HP", "V", "GF", "DF", "MP", "N"],
    servings: 12,
    prepMins: 15,
    cookMins: 0,
    nutrition: { calories: 130, protein: 8, carbs: 12, fat: 5 },
    ingredients: [
      "200g Medjool dates, pitted",
      "60g vanilla protein powder",
      "80g rolled oats",
      "50g almond butter",
      "2 tbsp cocoa powder",
      "1 tbsp chia seeds",
      "Pinch of salt",
    ],
    instructions: [
      "Blitz dates in a food processor until a paste forms.",
      "Add protein powder, oats, almond butter, cocoa, chia seeds, and salt.",
      "Pulse until a dough forms — if too dry, add 1 tsp water.",
      "Roll into 12 balls, place on a lined tray.",
      "Refrigerate 30 minutes until firm. Store in the fridge up to 1 week.",
    ],
  },
  {
    id: "s2",
    name: "Edamame & Cottage Cheese Dip",
    category: "snack",
    tags: ["HP", "V", "GF", "Q", "N"],
    servings: 2,
    prepMins: 5,
    cookMins: 0,
    nutrition: { calories: 180, protein: 18, carbs: 10, fat: 6 },
    ingredients: [
      "200g shelled edamame (cooked)",
      "150g low-fat cottage cheese",
      "1 garlic clove",
      "Juice of ½ lemon",
      "1 tbsp fresh mint",
      "Salt and pepper",
      "Carrot and celery sticks to serve",
    ],
    instructions: [
      "Blend edamame, cottage cheese, garlic, lemon juice, and mint until smooth.",
      "Season with salt and pepper.",
      "Serve with carrot and celery sticks.",
    ],
  },
  {
    id: "s3",
    name: "Turkey & Cheese Roll-Ups",
    category: "snack",
    tags: ["HP", "GF", "LC", "Q", "N"],
    servings: 1,
    prepMins: 5,
    cookMins: 0,
    nutrition: { calories: 190, protein: 24, carbs: 3, fat: 9 },
    ingredients: [
      "100g lean turkey breast slices",
      "30g reduced-fat cheddar, sliced",
      "1 tbsp wholegrain mustard",
      "4 baby gherkins",
    ],
    instructions: [
      "Spread a thin layer of mustard on each turkey slice.",
      "Place a slice of cheese and a gherkin at one end.",
      "Roll the turkey slice tightly around the filling.",
      "Secure with a cocktail stick if needed and serve.",
    ],
  },
  {
    id: "s4",
    name: "Hard Boiled Eggs with Hummus",
    category: "snack",
    tags: ["HP", "V", "GF", "DF", "MP", "Q"],
    servings: 1,
    prepMins: 2,
    cookMins: 10,
    nutrition: { calories: 220, protein: 18, carbs: 8, fat: 12 },
    ingredients: [
      "3 large eggs",
      "60g hummus",
      "Smoked paprika to sprinkle",
    ],
    instructions: [
      "Place eggs in cold water, bring to boil, simmer 8 minutes.",
      "Transfer to ice water, peel when cool.",
      "Serve with hummus, sprinkle paprika over eggs.",
    ],
    tip: "Hard boil a batch of 6 eggs at the start of the week for easy snacking.",
  },
  {
    id: "s5",
    name: "Protein Bark",
    category: "snack",
    tags: ["HP", "V", "GF", "DF", "MP"],
    servings: 8,
    prepMins: 10,
    cookMins: 0,
    nutrition: { calories: 160, protein: 10, carbs: 14, fat: 7 },
    ingredients: [
      "200g dark chocolate (70%+), melted",
      "60g chocolate protein powder",
      "3 tbsp almond butter",
      "50g almonds, roughly chopped",
      "30g dried cranberries",
      "Pinch of sea salt",
    ],
    instructions: [
      "Mix protein powder into melted dark chocolate until smooth.",
      "Stir in almond butter.",
      "Spread onto a lined baking tray, about 5mm thick.",
      "Scatter almonds, cranberries, and sea salt over the top.",
      "Refrigerate 1–2 hours until set, then break into 8 pieces.",
    ],
  },

  // ── SMOOTHIES ──────────────────────────────────────────────────────────────
  {
    id: "sm1",
    name: "Berry Protein Blast",
    category: "smoothie",
    tags: ["HP", "V", "GF", "DF", "Q", "N"],
    servings: 1,
    prepMins: 5,
    cookMins: 0,
    nutrition: { calories: 330, protein: 34, carbs: 36, fat: 4 },
    ingredients: [
      "30g vanilla protein powder",
      "150g frozen mixed berries",
      "1 banana",
      "200ml unsweetened almond milk",
      "1 tbsp flaxseeds",
      "Handful of ice",
    ],
    instructions: [
      "Add all ingredients to a blender.",
      "Blend on high speed for 60 seconds until smooth.",
      "Pour and drink immediately, or store in the fridge for up to 4 hours.",
    ],
  },
  {
    id: "sm2",
    name: "Chocolate Peanut Butter Shake",
    category: "smoothie",
    tags: ["HP", "V", "GF", "Q", "N"],
    servings: 1,
    prepMins: 5,
    cookMins: 0,
    nutrition: { calories: 420, protein: 38, carbs: 32, fat: 14 },
    ingredients: [
      "30g chocolate protein powder",
      "2 tbsp natural peanut butter",
      "1 medium banana, frozen",
      "250ml skimmed milk",
      "1 tsp cocoa powder",
      "Handful of ice",
    ],
    instructions: [
      "Blend all ingredients together until smooth and creamy.",
      "Add more milk if too thick.",
      "Drink immediately for best taste and texture.",
    ],
    tip: "Perfect post-workout shake — use frozen banana for a thicker consistency.",
  },
  {
    id: "sm3",
    name: "Green Power Smoothie",
    category: "smoothie",
    tags: ["HP", "V", "GF", "DF", "Q", "N", "LC"],
    servings: 1,
    prepMins: 5,
    cookMins: 0,
    nutrition: { calories: 290, protein: 30, carbs: 24, fat: 6 },
    ingredients: [
      "30g vanilla protein powder",
      "2 large handfuls fresh spinach",
      "½ cucumber, roughly chopped",
      "½ green apple, cored",
      "Juice of ½ lemon",
      "1 tsp matcha powder",
      "200ml coconut water",
      "Handful of ice",
    ],
    instructions: [
      "Add coconut water and spinach first, blend briefly.",
      "Add remaining ingredients and blend on high 60 seconds until smooth.",
      "Add more coconut water if needed to reach desired consistency.",
    ],
  },
  {
    id: "sm4",
    name: "Mango & Ginger Recovery Shake",
    category: "smoothie",
    tags: ["HP", "V", "GF", "DF", "Q", "N"],
    servings: 1,
    prepMins: 5,
    cookMins: 0,
    nutrition: { calories: 350, protein: 32, carbs: 42, fat: 4 },
    ingredients: [
      "30g vanilla protein powder",
      "200g frozen mango chunks",
      "1 tsp fresh ginger, grated",
      "½ tsp turmeric powder",
      "200ml unsweetened coconut milk",
      "Juice of ½ lime",
    ],
    instructions: [
      "Combine all ingredients in a blender.",
      "Blend until smooth — add a splash more coconut milk if too thick.",
      "Pour into a glass and drink straight away.",
    ],
    tip: "Turmeric and ginger both support recovery and reduce inflammation — ideal post-training.",
  },
  {
    id: "sm5",
    name: "Strawberry Cheesecake Protein Shake",
    category: "smoothie",
    tags: ["HP", "V", "GF", "Q", "N"],
    servings: 1,
    prepMins: 5,
    cookMins: 0,
    nutrition: { calories: 340, protein: 36, carbs: 30, fat: 8 },
    ingredients: [
      "30g strawberry or vanilla protein powder",
      "150g frozen strawberries",
      "100g low-fat cream cheese",
      "200ml skimmed milk",
      "1 tbsp honey",
      "1 tsp vanilla extract",
    ],
    instructions: [
      "Blend all ingredients together until smooth and creamy.",
      "Taste and adjust sweetness with honey if needed.",
      "Serve immediately.",
    ],
  },
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export const TAG_LABELS: Record<RecipeTag, string> = {
  GF: "Gluten Free",
  DF: "Dairy Free",
  LC: "Low Carb",
  MP: "Meal Prep",
  HP: "High Protein",
  V: "Vegetarian",
  Q: "Quick",
  N: "No Cook",
};

export const CATEGORY_LABELS: Record<RecipeCategory, string> = {
  breakfast: "Breakfast",
  lunch: "Lunch",
  dinner: "Dinner",
  snack: "Snacks",
  smoothie: "Smoothies",
};

export function getRecipesByCategory(category: RecipeCategory): Recipe[] {
  return recipes.filter((r) => r.category === category);
}

export function searchRecipes(query: string): Recipe[] {
  const q = query.toLowerCase();
  return recipes.filter(
    (r) =>
      r.name.toLowerCase().includes(q) ||
      r.ingredients.some((i) => i.toLowerCase().includes(q)) ||
      r.tags.some((t) => TAG_LABELS[t].toLowerCase().includes(q)),
  );
}
